### ISSUE TITLE
better fix for #147?

### ISSUE THREAD

**Issue by clixtec** [michaelklishin/quartz-mongodb#163]
Hi, I tried to build and use the current snapshot that includes the fix for issue #147, and I got this on startup:
`Caused by: org.quartz.SchedulerException: JobStore class 'com.novemberain.quartz.mongodb.MongoDBJobStore' props could not be configured. [See nested exception: java.lang.NoSuchMethodException: No setter for property 'checkInErrorHandler.class']
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:863)
        at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1525)
        at org.quartz.impl.StdSchedulerFactory.getDefaultScheduler(StdSchedulerFactory.java:1541)
        at co.skyhawk.ca.service.ReportingModule.configure(ReportingModule.java:38)
        ... 28 more
Caused by: java.lang.NoSuchMethodException: No setter for property 'checkInErrorHandler.class'
        at org.quartz.impl.StdSchedulerFactory.setBeanProps(StdSchedulerFactory.java:1413)
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:861)
        ... 31 more`

I believe an improved change to MongoDBJobStore and MongoStoreAssembler would be for the former to have a String property set by the usual StdSchedulerFactory mechanism, and simply read that property in createCheckInTask. Unfortunately the name of the property in quartz.properties would have to change slightly (drop the ".class"). I will submit a pull request shortly.

Thanks!

**Comment by titogarcia** [comment]
Thank you for this patch! I hope it is accepted.

**Comment by ikv163** [comment]
Thank you for this patch! I hope it is accepted.

**Comment by michaelklishin** [comment]
I will try to find a way to handle non-existent property files and follow the class property naming convention of Quartz core (`*.class`) but diving into Quartz takes a fair amount of effort every time I spent a year not looking at it.

**Comment by michaelklishin** [comment]
FTR, I have an unfinished follow-up/refactoring this this.
