### ISSUE TITLE
quartz no longer execute job when reconnected mongodb from disconnect for a while 

### ISSUE THREAD

**Issue by thloml** [michaelklishin/quartz-mongodb#171]
I close mongodb server when I run my application, for a while, console prints errors like this:

Exception in thread "SchedulerFactory_QuartzSchedulerThread" java.lang.AbstractMethodError: com.test.proj.baseservice.vo.TestMongoStore.getAcquireRetryDelay(I)J
	at org.quartz.core.QuartzSchedulerThread.computeDelayForRepeatedErrors(QuartzSchedulerThread.java:450)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
then I restart mongodb server but my scheduled job never run again .

  I think the reason is that the MongoDBJobStore doesn't implements getAcquireRetryDelay method in JobStore, but how did it compiled???

**Comment by MrZbb** [comment]
change quartz version from 2.3.0 to 2.1.0

**Comment by thloml** [comment]
Thanks, it works for me!
