### ISSUE TITLE
I need you help,May I ask what caused it?

### ISSUE THREAD

**Issue by AccountGc** [michaelklishin/quartz-mongodb#233]
` Node ecs-postoa-pro-dzbdserver-01-master1704349147264 could not check-in: waiting for replication timed out

com.mongodb.MongoWriteConcernException: waiting for replication timed out
        at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1016) ~[mongodb-driver-sync-4.6.1.jar!/:na]
        at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:994) ~[mongodb-driver-sync-4.6.1.jar!/:na]
        at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:579) ~[mongodb-driver-sync-4.6.1.jar!/:na]
        at com.novemberain.quartz.mongodb.dao.SchedulerDao.checkIn(SchedulerDao.java:71) ~[quartz-mongodb-2.2.0-rc2.jar!/:na]
        at com.novemberain.quartz.mongodb.cluster.CheckinTask.run(CheckinTask.java:32) ~[quartz-mongodb-2.2.0-rc2.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]

2024-01-14 14:48:53.082  INFO 1450778 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_ecs-postoa-pro-dzbdserver-01-master1704349147264 paused.
2024-01-14 14:49:03.630  INFO 1450778 --- [ionShutdownHook] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
2024-01-14 14:49:03.630  INFO 1450778 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_ecs-postoa-pro-dzbdserver-01-master1704349147264 shutting down.
2024-01-14 14:49:03.630  INFO 1450778 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_ecs-postoa-pro-dzbdserver-01-master1704349147264 paused.
2024-01-14 14:49:03.631  INFO 1450778 --- [ionShutdownHook] c.n.q.mongodb.cluster.CheckinExecutor    : Stopping CheckinExecutor for scheduler instance: ecs-postoa-pro-dzbdserver-01-master1704349147264
2024-01-14 14:49:03.726  INFO 1450778 --- [ionShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_ecs-postoa-pro-dzbdserver-01-master1704349147264 shutdown complete.`

**Comment by michaelklishin** [comment]
The README of this project very explicitly states that it is no longer maintained.
